### ISSUE TITLE
incorrect-fsf-address

### ISSUE THREAD

**Issue by rosset** [hdoria/HnTool#5]
Due https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address I need to tell upstream that hntool should fix this issue.

List of afftected files:
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/apache.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/remote.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/ssh.py
hntool.noarch: E: incorrect-fsf-address /usr/share/doc/hntool/LICENSE
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/util.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/ports.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/vsftpd.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/**init**.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/postgresql.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/proftpd.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/php.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/filesystems.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/authentication.py
hntool.noarch: E: incorrect-fsf-address /usr/bin/hntool
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/system-wide.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/output/terminal.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/core.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/output/**init**.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/output/html.py
hntool.noarch: E: incorrect-fsf-address /usr/lib/python2.7/site-packages/HnTool/modules/rule.py

Another question, I'm maintaining hntool package in Fedora, but upstream looks dead, do you have plans to keep hntool development or should I retire it from Fedora?
Thanks,

Filipe R.

**Comment by dogoncouch** [comment]
I have an easy fix for this but it does change every .py file slightly. I can submit it soon, if that won't get in anyone's way.

**Comment by hdoria** [comment]
Fixed.
